export const tickets = [
  {
    OrderID: '#SUP-2451',
    CustomerName: 'Emily Clark',
    Address: 'Unable to login with 2FA',
    priority: 'High',
    status: 'Pending',
    OrderDate: '04 Aug, 2025',
    DeliverDate: '08 Aug, 2025',
    billAmount: 1200,
  },
  {
    OrderID: '#SUP-2517',
    CustomerName: 'Lucas Graham',
    Address: 'Cannot upload profile image',
    priority: 'Medium',
    status: 'In Progress',
    OrderDate: '05 Aug, 2025',
    DeliverDate: '10 Aug, 2025',
    billAmount: 800,
  },
  {
    OrderID: '#SUP-2518',
    CustomerName: 'Nina Patel',
    Address: 'Incorrect invoice total shown',
    priority: 'High',
    status: 'Pending',
    OrderDate: '05 Aug, 2025',
    DeliverDate: '07 Aug, 2025',
    billAmount: 1500,
  },
  {
    OrderID: '#SUP-2519',
    CustomerName: 'Michael Foster',
    Address: 'Website not loading on Safari',
    priority: 'Low',
    status: 'Resolved',
    OrderDate: '04 Aug, 2025',
    DeliverDate: '06 Aug, 2025',
    billAmount: 600,
  },
  {
    OrderID: '#SUP-2520',
    CustomerName: 'Isabella Reed',
    Address: 'Cannot change account email',
    priority: 'Medium',
    status: 'In Progress',
    OrderDate: '03 Aug, 2025',
    DeliverDate: '08 Aug, 2025',
    billAmount: 1000,
  },
  {
    OrderID: '#SUP-2521',
    CustomerName: 'Olivia White',
    Address: "Can't access dashboard after update",
    priority: 'High',
    status: 'Escalated',
    OrderDate: '05 Aug, 2025',
    DeliverDate: '06 Aug, 2025',
    billAmount: 2000,
  },
  {
    OrderID: '#SUP-2522',
    CustomerName: 'Emma King',
    Address: 'Feature request: export as PDF',
    priority: 'Low',
    status: 'Closed',
    OrderDate: '01 Aug, 2025',
    DeliverDate: '05 Aug, 2025',
    billAmount: 500,
  },
  {
    OrderID: '#SUP-2523',
    CustomerName: 'Ava Sullivan',
    Address: 'App freezes when uploading files',
    priority: 'High',
    status: 'Pending',
    OrderDate: '05 Aug, 2025',
    DeliverDate: '09 Aug, 2025',
    billAmount: 1800,
  },
  {
    OrderID: '#SUP-2524',
    CustomerName: 'Sophie Bennett',
    Address: 'Missing transaction history',
    priority: 'Medium',
    status: 'In Progress',
    OrderDate: '04 Aug, 2025',
    DeliverDate: '08 Aug, 2025',
    billAmount: 900,
  },
  {
    OrderID: '#SUP-2525',
    CustomerName: 'Noah Allen',
    Address: 'Feedback form submission error',
    priority: 'Low',
    status: 'Resolved',
    OrderDate: '03 Aug, 2025',
    DeliverDate: '06 Aug, 2025',
    billAmount: 700,
  },
  {
    OrderID: '#SUP-2526',
    CustomerName: 'Ethan James',
    Address: "Can't generate report summary",
    priority: 'High',
    status: 'Escalated',
    OrderDate: '05 Aug, 2025',
    DeliverDate: '07 Aug, 2025',
    billAmount: 2200,
  },
  {
    OrderID: '#SUP-2527',
    CustomerName: 'Grace Carter',
    Address: 'Feature request: Dark mode toggle',
    priority: 'Low',
    status: 'Closed',
    OrderDate: '02 Aug, 2025',
    DeliverDate: '06 Aug, 2025',
    billAmount: 650,
  },
];
